name: Build & Deploy (Docker Hub → EC2)

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: prod-deploy
  cancel-in-progress: false

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Derive tag
        id: meta
        shell: bash
        run: |
          VERSION=$(grep -oP '(?<="version": ")[^"]+' package.json 2>/dev/null || echo "0.0.0")
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "TAG=v${VERSION}-${SHORT_SHA}" >> "$GITHUB_OUTPUT"

      # Prebuild outside Docker for clearer errors
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint & build
        run: |
          npm run lint --if-present || echo "lint skipped"
      - name: Build (needs NEXT_PUBLIC_* during prerender)
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Sanity push (canary)
        run: |
          docker pull hello-world
          docker tag hello-world ${{ vars.DOCKER_IMAGE }}:canary-${GITHUB_RUN_NUMBER}
          docker push ${{ vars.DOCKER_IMAGE }}:canary-${GITHUB_RUN_NUMBER}

      - name: Build & push
        uses: docker/build-push-action@v5
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.DOCKER_IMAGE }}:${{ steps.meta.outputs.TAG }}
            ${{ vars.DOCKER_IMAGE }}:prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Next build needs public keys at build time
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

  deploy_ec2:
    needs: build_push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          debug: true
          script: |
            set -e
            APP_DIR="${{ secrets.APP_DIR }}"
            IMAGE="${{ vars.DOCKER_IMAGE }}:prod"

            sudo mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            # Install docker + compose if missing
            if ! command -v docker >/dev/null 2>&1; then curl -fsSL https://get.docker.com | sh; fi
            if ! docker compose version >/dev/null 2>&1; then
              DOCKER_CONFIG=${HOME}/.docker
              mkdir -p $DOCKER_CONFIG/cli-plugins
              curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
              chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            fi

            # Ensure env is readable by SSH user
            sudo chown $USER:$USER /opt/shapeshifter/.env
            sudo chmod 600 /opt/shapeshifter/.env

            # Login only if your repo is private
            if [ -n "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then
              echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin || true
            fi

            # Ensure compose exists
            if [ ! -f docker-compose.yml ]; then
              cat > docker-compose.yml <<'YML'
            services:
              app:
                image: REPLACE_IMAGE
                container_name: shapeshifter
                restart: unless-stopped
                env_file:
                  - /opt/shapeshifter/.env
                ports:
                  - "127.0.0.1:3000:3000"
                healthcheck:
                  test: ["CMD-SHELL", "node -e \"http=require('http');http.get('http://127.0.0.1:3000/',r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))\""]
                  interval: 30s
                  timeout: 5s
                  retries: 5
                  start_period: 10s
            YML
            fi

            # Make sure the image tag is current
            sed -i "s|^\\s*image:.*$|    image: ${IMAGE}|" docker-compose.yml

            # Pull latest image & bring it up (idempotent)
            sudo docker compose -f docker-compose.yml pull app || true
            sudo docker compose -f docker-compose.yml up -d --no-deps --force-recreate app

            # Smoke check through Nginx if present, else direct
            echo "Waiting for container to appear..."
            for i in $(seq 1 30); do
              CID=$(sudo docker ps -qf name=^/shapeshifter$ || true)
              [ -n "$CID" ] && { echo "Container: $CID"; break; }
              sleep 2
              [ $i -eq 30 ] && { echo "Container didn't start"; sudo docker compose -f docker-compose.yml logs --tail=200 app || true; exit 1; }
            done

            HAS_HEALTH=$(sudo docker inspect shapeshifter --format '{{if .State.Health}}yes{{end}}' 2>/dev/null || true)
            if [ "$HAS_HEALTH" = "yes" ]; then
              echo "Waiting for Docker health=healthy..."
              for i in $(seq 1 45); do
                STATUS=$(sudo docker inspect shapeshifter --format '{{.State.Health.Status}}' 2>/dev/null || echo "unknown")
                echo "  health: $STATUS"
                [ "$STATUS" = "healthy" ] && break
                sleep 2
                [ $i -eq 45 ] && echo "Health still '$STATUS'; continuing to HTTP probe."
              done
            else
              echo "No healthcheck defined; skipping Docker health wait."
            fi

            echo "Probing app on localhost:3000..."
            for i in $(seq 1 30); do
              if curl -fsS http://127.0.0.1:3000/ -o /dev/null; then
                echo "App responds locally."
                break
              fi
              sleep 2
              [ $i -eq 30 ] && { echo "App never responded locally"; sudo docker compose -f docker-compose.yml logs --tail=200 app || true; exit 1; }
            done

            echo "Checking through Nginx (HTTPS)..."
            for i in $(seq 1 20); do
              if curl -fsS https://shapeshifter.djoshware.com -o /dev/null; then
                echo "HTTPS OK"
                exit 0
              fi
              sleep 3
            done

            echo "HTTPS still failing; nginx errors:"
            sudo tail -n 120 /var/log/nginx/error.log || true
            exit 1